//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab8.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="tns", ConfigurationName="ServiceReference1.SomeSoapService")]
    public interface SomeSoapService {
        
        // CODEGEN: Generating message contract since the operation addLogin is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="addLogin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Lab8.ServiceReference1.addLoginResponse1 addLogin(Lab8.ServiceReference1.addLogin1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="addLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<Lab8.ServiceReference1.addLoginResponse1> addLoginAsync(Lab8.ServiceReference1.addLogin1 request);
        
        // CODEGEN: Generating message contract since the operation isLoginFree is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="isLoginFree", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Lab8.ServiceReference1.isLoginFreeResponse1 isLoginFree(Lab8.ServiceReference1.isLoginFree1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="isLoginFree", ReplyAction="*")]
        System.Threading.Tasks.Task<Lab8.ServiceReference1.isLoginFreeResponse1> isLoginFreeAsync(Lab8.ServiceReference1.isLoginFree1 request);
        
        // CODEGEN: Generating message contract since the operation checkFile is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="checkFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Lab8.ServiceReference1.checkFileResponse1 checkFile(Lab8.ServiceReference1.checkFile1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="checkFile", ReplyAction="*")]
        System.Threading.Tasks.Task<Lab8.ServiceReference1.checkFileResponse1> checkFileAsync(Lab8.ServiceReference1.checkFile1 request);
        
        // CODEGEN: Generating message contract since the operation SendEmail is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="SendEmail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Lab8.ServiceReference1.SendEmailResponse1 SendEmail(Lab8.ServiceReference1.SendEmail1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SendEmail", ReplyAction="*")]
        System.Threading.Tasks.Task<Lab8.ServiceReference1.SendEmailResponse1> SendEmailAsync(Lab8.ServiceReference1.SendEmail1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="tns")]
    public partial class addLogin : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string loginField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
                this.RaisePropertyChanged("login");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="tns")]
    public partial class SendEmailResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sendEmailResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string SendEmailResult {
            get {
                return this.sendEmailResultField;
            }
            set {
                this.sendEmailResultField = value;
                this.RaisePropertyChanged("SendEmailResult");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="tns")]
    public partial class SendEmail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string subjectField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
                this.RaisePropertyChanged("subject");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="tns")]
    public partial class checkFileResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string checkFileResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string checkFileResult {
            get {
                return this.checkFileResultField;
            }
            set {
                this.checkFileResultField = value;
                this.RaisePropertyChanged("checkFileResult");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="tns")]
    public partial class checkFile : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string urlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("url");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="tns")]
    public partial class isLoginFreeResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<bool> isLoginFreeResultField;
        
        private bool isLoginFreeResultFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<bool> isLoginFreeResult {
            get {
                return this.isLoginFreeResultField;
            }
            set {
                this.isLoginFreeResultField = value;
                this.RaisePropertyChanged("isLoginFreeResult");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isLoginFreeResultSpecified {
            get {
                return this.isLoginFreeResultFieldSpecified;
            }
            set {
                this.isLoginFreeResultFieldSpecified = value;
                this.RaisePropertyChanged("isLoginFreeResultSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="tns")]
    public partial class isLoginFree : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string loginField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
                this.RaisePropertyChanged("login");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="tns")]
    public partial class addLoginResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string addLoginResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string addLoginResult {
            get {
                return this.addLoginResultField;
            }
            set {
                this.addLoginResultField = value;
                this.RaisePropertyChanged("addLoginResult");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addLogin1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="tns", Order=0)]
        public Lab8.ServiceReference1.addLogin addLogin;
        
        public addLogin1() {
        }
        
        public addLogin1(Lab8.ServiceReference1.addLogin addLogin) {
            this.addLogin = addLogin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addLoginResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="tns", Order=0)]
        public Lab8.ServiceReference1.addLoginResponse addLoginResponse;
        
        public addLoginResponse1() {
        }
        
        public addLoginResponse1(Lab8.ServiceReference1.addLoginResponse addLoginResponse) {
            this.addLoginResponse = addLoginResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isLoginFree1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="tns", Order=0)]
        public Lab8.ServiceReference1.isLoginFree isLoginFree;
        
        public isLoginFree1() {
        }
        
        public isLoginFree1(Lab8.ServiceReference1.isLoginFree isLoginFree) {
            this.isLoginFree = isLoginFree;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isLoginFreeResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="tns", Order=0)]
        public Lab8.ServiceReference1.isLoginFreeResponse isLoginFreeResponse;
        
        public isLoginFreeResponse1() {
        }
        
        public isLoginFreeResponse1(Lab8.ServiceReference1.isLoginFreeResponse isLoginFreeResponse) {
            this.isLoginFreeResponse = isLoginFreeResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checkFile1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="tns", Order=0)]
        public Lab8.ServiceReference1.checkFile checkFile;
        
        public checkFile1() {
        }
        
        public checkFile1(Lab8.ServiceReference1.checkFile checkFile) {
            this.checkFile = checkFile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checkFileResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="tns", Order=0)]
        public Lab8.ServiceReference1.checkFileResponse checkFileResponse;
        
        public checkFileResponse1() {
        }
        
        public checkFileResponse1(Lab8.ServiceReference1.checkFileResponse checkFileResponse) {
            this.checkFileResponse = checkFileResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendEmail1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="tns", Order=0)]
        public Lab8.ServiceReference1.SendEmail SendEmail;
        
        public SendEmail1() {
        }
        
        public SendEmail1(Lab8.ServiceReference1.SendEmail SendEmail) {
            this.SendEmail = SendEmail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendEmailResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="tns", Order=0)]
        public Lab8.ServiceReference1.SendEmailResponse SendEmailResponse;
        
        public SendEmailResponse1() {
        }
        
        public SendEmailResponse1(Lab8.ServiceReference1.SendEmailResponse SendEmailResponse) {
            this.SendEmailResponse = SendEmailResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SomeSoapServiceChannel : Lab8.ServiceReference1.SomeSoapService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SomeSoapServiceClient : System.ServiceModel.ClientBase<Lab8.ServiceReference1.SomeSoapService>, Lab8.ServiceReference1.SomeSoapService {
        
        public SomeSoapServiceClient() {
        }
        
        public SomeSoapServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SomeSoapServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SomeSoapServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SomeSoapServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab8.ServiceReference1.addLoginResponse1 Lab8.ServiceReference1.SomeSoapService.addLogin(Lab8.ServiceReference1.addLogin1 request) {
            return base.Channel.addLogin(request);
        }
        
        public Lab8.ServiceReference1.addLoginResponse addLogin(Lab8.ServiceReference1.addLogin addLogin1) {
            Lab8.ServiceReference1.addLogin1 inValue = new Lab8.ServiceReference1.addLogin1();
            inValue.addLogin = addLogin1;
            Lab8.ServiceReference1.addLoginResponse1 retVal = ((Lab8.ServiceReference1.SomeSoapService)(this)).addLogin(inValue);
            return retVal.addLoginResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lab8.ServiceReference1.addLoginResponse1> Lab8.ServiceReference1.SomeSoapService.addLoginAsync(Lab8.ServiceReference1.addLogin1 request) {
            return base.Channel.addLoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lab8.ServiceReference1.addLoginResponse1> addLoginAsync(Lab8.ServiceReference1.addLogin addLogin) {
            Lab8.ServiceReference1.addLogin1 inValue = new Lab8.ServiceReference1.addLogin1();
            inValue.addLogin = addLogin;
            return ((Lab8.ServiceReference1.SomeSoapService)(this)).addLoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab8.ServiceReference1.isLoginFreeResponse1 Lab8.ServiceReference1.SomeSoapService.isLoginFree(Lab8.ServiceReference1.isLoginFree1 request) {
            return base.Channel.isLoginFree(request);
        }
        
        public Lab8.ServiceReference1.isLoginFreeResponse isLoginFree(Lab8.ServiceReference1.isLoginFree isLoginFree1) {
            Lab8.ServiceReference1.isLoginFree1 inValue = new Lab8.ServiceReference1.isLoginFree1();
            inValue.isLoginFree = isLoginFree1;
            Lab8.ServiceReference1.isLoginFreeResponse1 retVal = ((Lab8.ServiceReference1.SomeSoapService)(this)).isLoginFree(inValue);
            return retVal.isLoginFreeResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lab8.ServiceReference1.isLoginFreeResponse1> Lab8.ServiceReference1.SomeSoapService.isLoginFreeAsync(Lab8.ServiceReference1.isLoginFree1 request) {
            return base.Channel.isLoginFreeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lab8.ServiceReference1.isLoginFreeResponse1> isLoginFreeAsync(Lab8.ServiceReference1.isLoginFree isLoginFree) {
            Lab8.ServiceReference1.isLoginFree1 inValue = new Lab8.ServiceReference1.isLoginFree1();
            inValue.isLoginFree = isLoginFree;
            return ((Lab8.ServiceReference1.SomeSoapService)(this)).isLoginFreeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab8.ServiceReference1.checkFileResponse1 Lab8.ServiceReference1.SomeSoapService.checkFile(Lab8.ServiceReference1.checkFile1 request) {
            return base.Channel.checkFile(request);
        }
        
        public Lab8.ServiceReference1.checkFileResponse checkFile(Lab8.ServiceReference1.checkFile checkFile1) {
            Lab8.ServiceReference1.checkFile1 inValue = new Lab8.ServiceReference1.checkFile1();
            inValue.checkFile = checkFile1;
            Lab8.ServiceReference1.checkFileResponse1 retVal = ((Lab8.ServiceReference1.SomeSoapService)(this)).checkFile(inValue);
            return retVal.checkFileResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lab8.ServiceReference1.checkFileResponse1> Lab8.ServiceReference1.SomeSoapService.checkFileAsync(Lab8.ServiceReference1.checkFile1 request) {
            return base.Channel.checkFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lab8.ServiceReference1.checkFileResponse1> checkFileAsync(Lab8.ServiceReference1.checkFile checkFile) {
            Lab8.ServiceReference1.checkFile1 inValue = new Lab8.ServiceReference1.checkFile1();
            inValue.checkFile = checkFile;
            return ((Lab8.ServiceReference1.SomeSoapService)(this)).checkFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab8.ServiceReference1.SendEmailResponse1 Lab8.ServiceReference1.SomeSoapService.SendEmail(Lab8.ServiceReference1.SendEmail1 request) {
            return base.Channel.SendEmail(request);
        }
        
        public Lab8.ServiceReference1.SendEmailResponse SendEmail(Lab8.ServiceReference1.SendEmail SendEmail1) {
            Lab8.ServiceReference1.SendEmail1 inValue = new Lab8.ServiceReference1.SendEmail1();
            inValue.SendEmail = SendEmail1;
            Lab8.ServiceReference1.SendEmailResponse1 retVal = ((Lab8.ServiceReference1.SomeSoapService)(this)).SendEmail(inValue);
            return retVal.SendEmailResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lab8.ServiceReference1.SendEmailResponse1> Lab8.ServiceReference1.SomeSoapService.SendEmailAsync(Lab8.ServiceReference1.SendEmail1 request) {
            return base.Channel.SendEmailAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lab8.ServiceReference1.SendEmailResponse1> SendEmailAsync(Lab8.ServiceReference1.SendEmail SendEmail) {
            Lab8.ServiceReference1.SendEmail1 inValue = new Lab8.ServiceReference1.SendEmail1();
            inValue.SendEmail = SendEmail;
            return ((Lab8.ServiceReference1.SomeSoapService)(this)).SendEmailAsync(inValue);
        }
    }
}
